### ISSUE TITLE
[UI/UX-Console] The search field remains large when the sidebar is shrunk.

### ISSUE THREAD

**Issue by ramazansancar** [minio/object-browser#3552]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior

It may be that the search field shrinks and the sidebar expands when clicked on.

## Current Behavior

If the sidebar shrinks while Search is selected, it looks bad visually.

![Image](https://github.com/user-attachments/assets/2f17c25c-566c-4504-8c4b-d3a466f27c50)

## Possible Solution

It may be that the search field shrinks and the sidebar expands when clicked on.

## Steps to Reproduce (for bugs)

1. Minimize Sidebar
2. Type something in search.

## Your Environment

* Version used (`minio --version`): 9.6 (latest)
* Server setup and configuration: Docker Compose
* Operating System and version (`uname -a`): Windows 10 - Google Chrome 130.0.6723.117

```yml
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    ports:
      - "19000:9000"
      - "19001:9001"
    environment:
      MINIO_ROOT_USER: *****
      MINIO_ROOT_PASSWORD: *****
    command: server /data --console-address ":9001"
    volumes:
      - ./YYYYY:/data

volumes:
  YYYYY:
    driver: local

```
